os: linux
language: java
sudo: required
env:
  matrix:
    - DISPLAY=:99.0
dist: trusty
notifications:
  email:
    on_success: never
    on_cancel: never
    on_error: always
    on_start: never
    on_failure: always
addons:
  chrome: stable
install:
  #DOWNLOAD AND INSTALL ALL REQUIRED DRIVERS
  - wget -N http://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - npm install -g allure-commandline --save-dev
before_script:
  #GUI & VIRTUAL BROWSER
  - sh -e /etc/init.d/xvfb start
  #GIVE Xvfb TIME TO START
  - sleep 3
  - echo ========================================================================
  - echo =========================BUILD EXECUTION STARTED========================
  - echo ========================================================================
script:
  #RUN GRADLE
  - ./gradlew check
after_script:
  - echo ========================================================================
  - echo ========================BUILD EXECUTION FINISHED========================
  - echo ========================================================================
  - chmod 777 .travis/deploy.sh
  - echo ========================================================================
  - echo =========================UPLOADING TEST REPORTS=========================
  - echo ========================================================================
  - .travis/deploy.sh